### ISSUE TITLE
Outliers detection and behaviour analytic - Not updating Lower,Upper,Avg values

### ISSUE THREAD

**Issue by s2835648** [guilhemmarchand/trackme#240] opened 2021-02-10 08:29 UTC
We are facing a issue where the outliers detection overview never displays results/functions correctly. It seems the values for lower band, upper band and avg are always the same, even if we adjust the spanning periods.
![image](https://user-images.githubusercontent.com/7518441/107483561-8d451480-6b81-11eb-888a-dda781ab306d.png)

This behavior is across all sources.  
![image](https://user-images.githubusercontent.com/7518441/107483975-14928800-6b82-11eb-99b8-e3a8959fb86c.png)

**Current troubleshooting steps taken:**
- manually run TrackMe - Volume -Xd Outliers update tracker
- Run both short/long term trackers
-  Recreated trackme_summary, trackeme_metrics indexes

**Version:**
- 1.2.33 (However behavior was always detected in version .32

thank you!

**Comment by guilhemmarchand** [comment] 2021-02-10 09:47
Hi @s2835648 

Right, this is suspcious, can you please run the following searches and share the results, take one data source that is active as for the target and trouble shooting purposes:

1. time range picker: last 7d

```
| mstats stdev(trackme.eventcount_4h) as stdev, avg(trackme.eventcount_4h) as avg where `trackme_metrics_idx` object_category="data_source" object="firewall:pan:traffic" enable_behaviour_analytic="true" OutlierTimePeriod="-7d" earliest="-7d" latest="now" by object_category, object 
| inputlookup trackme_data_source_monitoring append=1 where OutlierTimePeriod="-7d" 
| inputlookup trackme_host_monitoring append=1 where OutlierTimePeriod="-7d" 
| fields + object_category, object, stdev, avg, OutlierTimePeriod, OutlierMinEventCount, OutlierLowerThresholdMultiplier, OutlierUpperThresholdMultiplier, data_name, data_host 
| eval object=case((isnull(object) AND (object_category == "data_source")),data_name,(isnull(object) AND (object_category == "data_host")),data_host,isnotnull(object),object) 
| stats first(stdev) as stdev, first(avg) as avg, first(OutlierTimePeriod) as OutlierTimePeriod, first(OutlierMinEventCount) as OutlierMinEventCount, first(OutlierLowerThresholdMultiplier) as OutlierLowerThresholdMultiplier, first(OutlierUpperThresholdMultiplier) as OutlierUpperThresholdMultiplier by object_category, object 
| where isnotnull(OutlierTimePeriod) 
| eval OutlierLowerThresholdMultiplier=if(isnum(OutlierLowerThresholdMultiplier),OutlierLowerThresholdMultiplier,4), OutlierUpperThresholdMultiplier=if(isnum(OutlierUpperThresholdMultiplier),OutlierUpperThresholdMultiplier,4), lowerBound=(avg - (stdev * exact(OutlierLowerThresholdMultiplier))), upperBound=(avg + (stdev * exact(OutlierUpperThresholdMultiplier))), lowerBound=if((lowerBound < 0),0,lowerBound), lowerBound=if((isnum(OutlierMinEventCount) AND (OutlierMinEventCount > 0)),OutlierMinEventCount,lowerBound), OutlierMinEventCount=if(isnum(OutlierMinEventCount),OutlierMinEventCount,0), update_time=now()

| search object_category="data_source" object="firewall:pan:traffic"
```

2. time range picker last 7 days

```
| mstats avg(trackme.eventcount_4h) as avg where `trackme_metrics_idx` object_category="data_source" object="firewall:pan:traffic" enable_behaviour_analytic="true" OutlierTimePeriod="-7d" earliest="-7d" latest="now" by object_category, object span=4h
| timechart avg(avg) as avg by object span=4h
```

3. time range last 7d (this done looks at all object)

```
| mcatalog values(metric_name) as metrics values(_dims) as dims where index=* metric_name=trackme.* by index, object, object_category
| stats values(index) as index, dc(object) as dcount_objects, values(object_category) as object_category, values(metrics) as metrics, values(dims) as dims
```

Thanks

Guilhem

**Comment by s2835648** [comment] 2021-02-10 12:44
Thanks for the quick response @guilhemmarchand 

Here you go!

**1)*
![image](https://user-images.githubusercontent.com/7518441/107511237-829c7680-6ba5-11eb-8c57-f68777572f53.png)

**2)**
![image](https://user-images.githubusercontent.com/7518441/107511499-dad37880-6ba5-11eb-9e93-52778ee5be4b.png)

**3)**
![image](https://user-images.githubusercontent.com/7518441/107511644-0ce4da80-6ba6-11eb-8a49-3b7d7833751a.png)

Much appreciated for your support!

**Comment by guilhemmarchand** [comment] 2021-02-10 18:03
@s2835648 

As far as I can tell, your deployment is not generating the metrics anymore, but it did it briefly, which is why you get the exact same results between the lower bound and upper bound.

I suspect that the target index was either changed or not created.

TrackMe requires a metric index, by default it expects:

```
[trackme_metrics]
coldPath = $SPLUNK_DB/trackme_metrics/colddb
homePath = $SPLUNK_DB/trackme_metrics/db
thawedPath = $SPLUNK_DB/trackme_metrics/thaweddb
datatype = metric
```

Note that this is a metrc index and not an event index. (datatype = metric)

Then TrackMe uses a macro to access to this data:

```
# trackMe metric index, customise its value depending on your preference
# default to trackme_metrics which has to be created
[trackme_metrics_idx]
definition = index="trackme_metrics"
iseval = 0
```

I suspect you have a misconfiguration or the index target was changed:

`| mcatalog values(metric_name) (_dims) where index=* metric_name=trackme.* earliest=-24h latest=now by index
`

--> please share the result of that

*expected result:*

![image](https://user-images.githubusercontent.com/7503059/107551102-c012fb00-6bc9-11eb-9718-e7ec7e4e9d93.png)

These metrics are generated by TrackMe everytime a tracker runs, if you changed the index name you need to update the macro to reflect that.

These metrics are collected by the mcollect command, which is similar to summary data for metrics, TrackMe uses the collect command to generates different logs too (by default in the trackme_summary index)

Double check this please.

Guilhem

**Comment by s2835648** [comment] 2021-02-11 08:26
Hi @guilhemmarchand 

Good news! The outline detection is now working. We had the TrackMe_Metrics index configured to store it's logs in Smart Store Storage. Once I update the index to store locally, it worked straight away. Thank you very much for your assistants :)

**Comment by guilhemmarchand** [comment] 2021-02-11 08:42
Wonderful @s2835648 

Glad the issue is fixed, closing it now, do not hesitate if you have any further issues, enhacements requests or remarks etc 

Guilhem

**Closed by guilhemmarchand** 2021-02-11 08:42 UTC
Labels: question
